/**
 * Currency and country lookup — GENERATED by scripts/gen-currencies.mjs.
 *
 * 144 currencies, every one of which Yahoo Finance quotes against USD
 * (verified: 143/143 supported, probed in 2.1s).
 *
 * Each row carries the ISO code, the CLDR display name, and the countries and
 * territories that use it. All three are searchable, so "euro", "EUR",
 * "Germany" and "European Union" all resolve to the same row — which is the
 * whole feature, and the reason it needs no language model. It is a substring
 * match over a static table: deterministic, instant, offline and free.
 */

export type Currency = {
  /** ISO 4217 code, e.g. "INR". */
  code: string;
  /** CLDR display name, e.g. "Indian Rupee". */
  name: string;
  /** Countries and territories, comma-separated — searchable aliases. */
  countries: string;
};

export const CURRENCIES: Currency[] = [
  {
    "code": "AED",
    "name": "United Arab Emirates Dirham",
    "countries": "United Arab Emirates, UAE, Dubai, Abu Dhabi"
  },
  {
    "code": "AFN",
    "name": "Afghan Afghani",
    "countries": "Afghanistan"
  },
  {
    "code": "ALL",
    "name": "Albanian Lek",
    "countries": "Albania"
  },
  {
    "code": "AMD",
    "name": "Armenian Dram",
    "countries": "Armenia"
  },
  {
    "code": "AOA",
    "name": "Angolan Kwanza",
    "countries": "Angola"
  },
  {
    "code": "ARS",
    "name": "Argentine Peso",
    "countries": "Argentina"
  },
  {
    "code": "AUD",
    "name": "Australian Dollar",
    "countries": "Australia"
  },
  {
    "code": "AZN",
    "name": "Azerbaijani Manat",
    "countries": "Azerbaijan"
  },
  {
    "code": "BAM",
    "name": "Bosnia-Herzegovina Convertible Mark",
    "countries": "Bosnia and Herzegovina"
  },
  {
    "code": "BBD",
    "name": "Barbadian Dollar",
    "countries": "Barbados"
  },
  {
    "code": "BDT",
    "name": "Bangladeshi Taka",
    "countries": "Bangladesh"
  },
  {
    "code": "BGN",
    "name": "Bulgarian Lev",
    "countries": "Bulgaria"
  },
  {
    "code": "BHD",
    "name": "Bahraini Dinar",
    "countries": "Bahrain"
  },
  {
    "code": "BIF",
    "name": "Burundian Franc",
    "countries": "Burundi"
  },
  {
    "code": "BND",
    "name": "Brunei Dollar",
    "countries": "Brunei"
  },
  {
    "code": "BOB",
    "name": "Bolivian Boliviano",
    "countries": "Bolivia"
  },
  {
    "code": "BRL",
    "name": "Brazilian Real",
    "countries": "Brazil"
  },
  {
    "code": "BSD",
    "name": "Bahamian Dollar",
    "countries": "Bahamas"
  },
  {
    "code": "BTN",
    "name": "Bhutanese Ngultrum",
    "countries": "Bhutan"
  },
  {
    "code": "BWP",
    "name": "Botswanan Pula",
    "countries": "Botswana"
  },
  {
    "code": "BYN",
    "name": "Belarusian Ruble",
    "countries": "Belarus"
  },
  {
    "code": "BZD",
    "name": "Belize Dollar",
    "countries": "Belize"
  },
  {
    "code": "CAD",
    "name": "Canadian Dollar",
    "countries": "Canada"
  },
  {
    "code": "CDF",
    "name": "Congolese Franc",
    "countries": "Democratic Republic of the Congo, DRC"
  },
  {
    "code": "CHF",
    "name": "Swiss Franc",
    "countries": "Switzerland, Liechtenstein"
  },
  {
    "code": "CLP",
    "name": "Chilean Peso",
    "countries": "Chile"
  },
  {
    "code": "CNY",
    "name": "Chinese Yuan",
    "countries": "China"
  },
  {
    "code": "COP",
    "name": "Colombian Peso",
    "countries": "Colombia"
  },
  {
    "code": "CRC",
    "name": "Costa Rican Colón",
    "countries": "Costa Rica"
  },
  {
    "code": "CUP",
    "name": "Cuban Peso",
    "countries": "Cuba"
  },
  {
    "code": "CVE",
    "name": "Cape Verdean Escudo",
    "countries": "Cape Verde"
  },
  {
    "code": "CZK",
    "name": "Czech Koruna",
    "countries": "Czech Republic, Czechia"
  },
  {
    "code": "DJF",
    "name": "Djiboutian Franc",
    "countries": "Djibouti"
  },
  {
    "code": "DKK",
    "name": "Danish Krone",
    "countries": "Denmark"
  },
  {
    "code": "DOP",
    "name": "Dominican Peso",
    "countries": "Dominican Republic"
  },
  {
    "code": "DZD",
    "name": "Algerian Dinar",
    "countries": "Algeria"
  },
  {
    "code": "EGP",
    "name": "Egyptian Pound",
    "countries": "Egypt"
  },
  {
    "code": "ERN",
    "name": "Eritrean Nakfa",
    "countries": "Eritrea"
  },
  {
    "code": "ETB",
    "name": "Ethiopian Birr",
    "countries": "Ethiopia"
  },
  {
    "code": "EUR",
    "name": "Euro",
    "countries": "European Union, Eurozone, Germany, France, Italy, Spain, Netherlands, Belgium, Austria, Ireland, Portugal, Greece, Finland, Slovakia, Slovenia, Estonia, Latvia, Lithuania, Luxembourg, Cyprus, Malta, Croatia"
  },
  {
    "code": "FJD",
    "name": "Fijian Dollar",
    "countries": "Fiji"
  },
  {
    "code": "GBP",
    "name": "British Pound",
    "countries": "United Kingdom, UK, Britain, England, Scotland, Wales, Northern Ireland"
  },
  {
    "code": "GEL",
    "name": "Georgian Lari",
    "countries": "Georgia"
  },
  {
    "code": "GHS",
    "name": "Ghanaian Cedi",
    "countries": "Ghana"
  },
  {
    "code": "GMD",
    "name": "Gambian Dalasi",
    "countries": "Gambia"
  },
  {
    "code": "GNF",
    "name": "Guinean Franc",
    "countries": "Guinea"
  },
  {
    "code": "GTQ",
    "name": "Guatemalan Quetzal",
    "countries": "Guatemala"
  },
  {
    "code": "GYD",
    "name": "Guyanaese Dollar",
    "countries": "Guyana"
  },
  {
    "code": "HKD",
    "name": "Hong Kong Dollar",
    "countries": "Hong Kong"
  },
  {
    "code": "HNL",
    "name": "Honduran Lempira",
    "countries": "Honduras"
  },
  {
    "code": "HRK",
    "name": "Croatian Kuna",
    "countries": "Croatia"
  },
  {
    "code": "HTG",
    "name": "Haitian Gourde",
    "countries": "Haiti"
  },
  {
    "code": "HUF",
    "name": "Hungarian Forint",
    "countries": "Hungary"
  },
  {
    "code": "IDR",
    "name": "Indonesian Rupiah",
    "countries": "Indonesia"
  },
  {
    "code": "ILS",
    "name": "Israeli New Shekel",
    "countries": "Israel"
  },
  {
    "code": "INR",
    "name": "Indian Rupee",
    "countries": "India"
  },
  {
    "code": "IQD",
    "name": "Iraqi Dinar",
    "countries": "Iraq"
  },
  {
    "code": "IRR",
    "name": "Iranian Rial",
    "countries": "Iran"
  },
  {
    "code": "ISK",
    "name": "Icelandic Króna",
    "countries": "Iceland"
  },
  {
    "code": "JMD",
    "name": "Jamaican Dollar",
    "countries": "Jamaica"
  },
  {
    "code": "JOD",
    "name": "Jordanian Dinar",
    "countries": "Jordan"
  },
  {
    "code": "JPY",
    "name": "Japanese Yen",
    "countries": "Japan"
  },
  {
    "code": "KES",
    "name": "Kenyan Shilling",
    "countries": "Kenya"
  },
  {
    "code": "KGS",
    "name": "Kyrgyz Som",
    "countries": "Kyrgyzstan"
  },
  {
    "code": "KHR",
    "name": "Cambodian Riel",
    "countries": "Cambodia"
  },
  {
    "code": "KMF",
    "name": "Comorian Franc",
    "countries": "Comoros"
  },
  {
    "code": "KRW",
    "name": "South Korean Won",
    "countries": "South Korea, Korea"
  },
  {
    "code": "KWD",
    "name": "Kuwaiti Dinar",
    "countries": "Kuwait"
  },
  {
    "code": "KZT",
    "name": "Kazakhstani Tenge",
    "countries": "Kazakhstan"
  },
  {
    "code": "LAK",
    "name": "Laotian Kip",
    "countries": "Laos"
  },
  {
    "code": "LBP",
    "name": "Lebanese Pound",
    "countries": "Lebanon"
  },
  {
    "code": "LKR",
    "name": "Sri Lankan Rupee",
    "countries": "Sri Lanka"
  },
  {
    "code": "LRD",
    "name": "Liberian Dollar",
    "countries": "Liberia"
  },
  {
    "code": "LSL",
    "name": "Lesotho Loti",
    "countries": "Lesotho"
  },
  {
    "code": "LYD",
    "name": "Libyan Dinar",
    "countries": "Libya"
  },
  {
    "code": "MAD",
    "name": "Moroccan Dirham",
    "countries": "Morocco"
  },
  {
    "code": "MDL",
    "name": "Moldovan Leu",
    "countries": "Moldova"
  },
  {
    "code": "MGA",
    "name": "Malagasy Ariary",
    "countries": "Madagascar"
  },
  {
    "code": "MKD",
    "name": "Macedonian Denar",
    "countries": "North Macedonia"
  },
  {
    "code": "MMK",
    "name": "Myanmar Kyat",
    "countries": "Myanmar, Burma"
  },
  {
    "code": "MNT",
    "name": "Mongolian Tugrik",
    "countries": "Mongolia"
  },
  {
    "code": "MOP",
    "name": "Macanese Pataca",
    "countries": "Macau"
  },
  {
    "code": "MUR",
    "name": "Mauritian Rupee",
    "countries": "Mauritius"
  },
  {
    "code": "MVR",
    "name": "Maldivian Rufiyaa",
    "countries": "Maldives"
  },
  {
    "code": "MWK",
    "name": "Malawian Kwacha",
    "countries": "Malawi"
  },
  {
    "code": "MXN",
    "name": "Mexican Peso",
    "countries": "Mexico"
  },
  {
    "code": "MYR",
    "name": "Malaysian Ringgit",
    "countries": "Malaysia"
  },
  {
    "code": "MZN",
    "name": "Mozambican Metical",
    "countries": "Mozambique"
  },
  {
    "code": "NAD",
    "name": "Namibian Dollar",
    "countries": "Namibia"
  },
  {
    "code": "NGN",
    "name": "Nigerian Naira",
    "countries": "Nigeria"
  },
  {
    "code": "NIO",
    "name": "Nicaraguan Córdoba",
    "countries": "Nicaragua"
  },
  {
    "code": "NOK",
    "name": "Norwegian Krone",
    "countries": "Norway"
  },
  {
    "code": "NPR",
    "name": "Nepalese Rupee",
    "countries": "Nepal"
  },
  {
    "code": "NZD",
    "name": "New Zealand Dollar",
    "countries": "New Zealand"
  },
  {
    "code": "OMR",
    "name": "Omani Rial",
    "countries": "Oman"
  },
  {
    "code": "PAB",
    "name": "Panamanian Balboa",
    "countries": "Panama"
  },
  {
    "code": "PEN",
    "name": "Peruvian Sol",
    "countries": "Peru"
  },
  {
    "code": "PGK",
    "name": "Papua New Guinean Kina",
    "countries": "Papua New Guinea"
  },
  {
    "code": "PHP",
    "name": "Philippine Peso",
    "countries": "Philippines"
  },
  {
    "code": "PKR",
    "name": "Pakistani Rupee",
    "countries": "Pakistan"
  },
  {
    "code": "PLN",
    "name": "Polish Zloty",
    "countries": "Poland"
  },
  {
    "code": "PYG",
    "name": "Paraguayan Guarani",
    "countries": "Paraguay"
  },
  {
    "code": "QAR",
    "name": "Qatari Riyal",
    "countries": "Qatar"
  },
  {
    "code": "RON",
    "name": "Romanian Leu",
    "countries": "Romania"
  },
  {
    "code": "RSD",
    "name": "Serbian Dinar",
    "countries": "Serbia"
  },
  {
    "code": "RUB",
    "name": "Russian Ruble",
    "countries": "Russia"
  },
  {
    "code": "RWF",
    "name": "Rwandan Franc",
    "countries": "Rwanda"
  },
  {
    "code": "SAR",
    "name": "Saudi Riyal",
    "countries": "Saudi Arabia"
  },
  {
    "code": "SBD",
    "name": "Solomon Islands Dollar",
    "countries": "Solomon Islands"
  },
  {
    "code": "SCR",
    "name": "Seychellois Rupee",
    "countries": "Seychelles"
  },
  {
    "code": "SDG",
    "name": "Sudanese Pound",
    "countries": "Sudan"
  },
  {
    "code": "SEK",
    "name": "Swedish Krona",
    "countries": "Sweden"
  },
  {
    "code": "SGD",
    "name": "Singapore Dollar",
    "countries": "Singapore"
  },
  {
    "code": "SLL",
    "name": "Sierra Leonean Leone (1964—2022)",
    "countries": "Sierra Leone"
  },
  {
    "code": "SOS",
    "name": "Somali Shilling",
    "countries": "Somalia"
  },
  {
    "code": "SRD",
    "name": "Surinamese Dollar",
    "countries": "Suriname"
  },
  {
    "code": "STN",
    "name": "São Tomé & Príncipe Dobra",
    "countries": "Sao Tome and Principe"
  },
  {
    "code": "SYP",
    "name": "Syrian Pound",
    "countries": "Syria"
  },
  {
    "code": "SZL",
    "name": "Swazi Lilangeni",
    "countries": "Eswatini, Swaziland"
  },
  {
    "code": "THB",
    "name": "Thai Baht",
    "countries": "Thailand"
  },
  {
    "code": "TJS",
    "name": "Tajikistani Somoni",
    "countries": "Tajikistan"
  },
  {
    "code": "TMT",
    "name": "Turkmenistani Manat",
    "countries": "Turkmenistan"
  },
  {
    "code": "TND",
    "name": "Tunisian Dinar",
    "countries": "Tunisia"
  },
  {
    "code": "TOP",
    "name": "Tongan Paʻanga",
    "countries": "Tonga"
  },
  {
    "code": "TRY",
    "name": "Turkish Lira",
    "countries": "Turkey, Türkiye"
  },
  {
    "code": "TTD",
    "name": "Trinidad & Tobago Dollar",
    "countries": "Trinidad and Tobago"
  },
  {
    "code": "TWD",
    "name": "New Taiwan Dollar",
    "countries": "Taiwan"
  },
  {
    "code": "TZS",
    "name": "Tanzanian Shilling",
    "countries": "Tanzania"
  },
  {
    "code": "UAH",
    "name": "Ukrainian Hryvnia",
    "countries": "Ukraine"
  },
  {
    "code": "UGX",
    "name": "Ugandan Shilling",
    "countries": "Uganda"
  },
  {
    "code": "USD",
    "name": "US Dollar",
    "countries": "United States, USA, America, Ecuador, El Salvador, Zimbabwe"
  },
  {
    "code": "UYU",
    "name": "Uruguayan Peso",
    "countries": "Uruguay"
  },
  {
    "code": "UZS",
    "name": "Uzbekistani Som",
    "countries": "Uzbekistan"
  },
  {
    "code": "VES",
    "name": "Venezuelan Bolívar",
    "countries": "Venezuela"
  },
  {
    "code": "VND",
    "name": "Vietnamese Dong",
    "countries": "Vietnam"
  },
  {
    "code": "VUV",
    "name": "Vanuatu Vatu",
    "countries": "Vanuatu"
  },
  {
    "code": "WST",
    "name": "Samoan Tala",
    "countries": "Samoa"
  },
  {
    "code": "XAF",
    "name": "Central African CFA Franc",
    "countries": "Central African CFA, Cameroon, Chad, Congo, Gabon, Equatorial Guinea, Central African Republic"
  },
  {
    "code": "XCD",
    "name": "East Caribbean Dollar",
    "countries": "Eastern Caribbean, Antigua, Saint Lucia, Grenada, Dominica, Saint Kitts, Saint Vincent"
  },
  {
    "code": "XOF",
    "name": "West African CFA Franc",
    "countries": "West African CFA, Senegal, Ivory Coast, Mali, Burkina Faso, Benin, Niger, Togo, Guinea-Bissau"
  },
  {
    "code": "XPF",
    "name": "CFP Franc",
    "countries": "French Polynesia, New Caledonia, Wallis and Futuna"
  },
  {
    "code": "YER",
    "name": "Yemeni Rial",
    "countries": "Yemen"
  },
  {
    "code": "ZAR",
    "name": "South African Rand",
    "countries": "South Africa"
  },
  {
    "code": "ZMW",
    "name": "Zambian Kwacha",
    "countries": "Zambia"
  }
];

export const CURRENCY_CODES = CURRENCIES.map((c) => c.code);

const BY_CODE = new Map(CURRENCIES.map((c) => [c.code, c]));

export const currencyByCode = (code: string): Currency | undefined =>
  BY_CODE.get(code.toUpperCase());

/**
 * Search by code, currency name, or country.
 *
 * Ranking order matters more than it looks. An exact *country alias* has to
 * outrank a name *prefix*, or "uk" returns the Ukrainian Hryvnia — "Ukrainian"
 * starts with those letters — above the British Pound, which is certainly not
 * what someone typing "uk" meant. Whole-word matches beat partial ones at
 * every tier for the same reason.
 */
export function searchCurrencies(query: string, limit = 8): Currency[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored: Array<{ c: Currency; score: number }> = [];

  for (const c of CURRENCIES) {
    const code = c.code.toLowerCase();
    const name = c.name.toLowerCase();
    const aliases = c.countries.toLowerCase().split(", ");

    let score = 0;
    if (code === q) score = 100;
    else if (aliases.some((x) => x === q)) score = 85;
    else if (name === q) score = 82;
    else if (code.startsWith(q)) score = 80;
    else if (name.startsWith(q)) score = 75;
    else if (aliases.some((x) => x.startsWith(q))) score = 70;
    else if (name.includes(q)) score = 50;
    else if (aliases.some((x) => x.includes(q))) score = 40;

    if (score > 0) scored.push({ c, score });
  }

  return scored
    .sort((a, b) => b.score - a.score || a.c.code.localeCompare(b.c.code))
    .slice(0, limit)
    .map((s) => s.c);
}
